### ISSUE TITLE
configure and portability

### ISSUE THREAD

**Issue by dark-w** [cc-practice/jay-liu#3]
Makefile还需要支持：
1. make clean和make distclean (两者有什么区别？)
1. make install和uninstall

**Comment by conke** [comment]
谁来说说Makefile的几个常见target?

**Comment by dark-w** [comment]
> 谁来说说Makefile的几个常见target?

install, clean, distclean, check, distcheck, uninstall...

**Comment by troy-song** [comment]
可执行文件
*.o
clean
install

**Comment by jie-smile** [comment]
我现在所知道的：
clean：清除上次的make命令所产生的object文件（后缀为“.o”的文件）及可执行文件。
distclean：在make clean的基础上也将configure生成的文件全部删除掉。
install：将生成的可执行文件放入默认或指定的目录下。
check：运行测试Makefile生成的文件。
all：不知道怎么描述。

**Comment by conke** [comment]
> 在make clean的基础上也将configure生成的文件全部删除掉。

对！比如（最典型）Makefile

**Comment by conke** [comment]
> 我现在所知道的：
> clean：清除上次的make命令所产生的object文件（后缀为“.o”的文件）及可执行文件。
> distclean：在make clean的基础上也将configure生成的文件全部删除掉。
> install：将生成的可执行文件放入默认或指定的目录下。
> check：运行测试Makefile生成的文件。
> all：不知道怎么描述。

**Comment by conke** [comment]
> all：不知道怎么描述

前一个PR中没有用到all吗？

**Comment by jie-smile** [comment]
> > all：不知道怎么描述
> 
> 前一个PR中没有用到all吗？

我知道" all "的用法，但我想不出要怎么描述。
